### ISSUE TITLE
Installing App in Background in Rooted Devices

### ISSUE THREAD

**Issue by kotanaavatharam** [paulononaka/Android-InstallInBackgroundSample#5]
I tested the above project in my rooted device(Android 6.0), but I am getting below error. Can you please help me on this.

java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.github.paulononaka.installapkinbackground.apihelper.ApplicationManager.installPackage(ApplicationManager.java:326)
at com.github.paulononaka.installapkinbackground.apihelper.ApplicationManager.installPackage(ApplicationManager.java:322)
at com.github.paulononaka.installapkinbackground.apihelper.ApplicationManager.installPackage(ApplicationManager.java:316)
at com.github.paulononaka.installapkinbackground.MainActivity$2.onClick(MainActivity.java:47)
at android.view.View.performClick(View.java:5207)
at android.view.View$PerformClick.run(View.java:21168)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.SecurityException: Neither user 10127 nor current process has android.permission.INSTALL_PACKAGES.
at android.os.Parcel.readException(Parcel.java:1620)
at android.os.Parcel.readException(Parcel.java:1573)
at android.content.pm.IPackageManager$Stub$Proxy.installPackage(IPackageManager.java:3436)
at android.app.ApplicationPackageManager.installCommon(ApplicationPackageManager.java:1400)
at android.app.ApplicationPackageManager.installPackage(ApplicationPackageManager.java:1339)

**Comment by smer4ik** [comment]
I had the same error, insert in manifest     
> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
You cant acces you apk file)

**Comment by dhruvkaushal11** [comment]
You are getting android.permission.INSTALL_PACKAGES error because you are running /data/app/base.apk instead of /system/app/base.apk.

- Make a fresh install
- Copy base.apk from /data/app/com.github.paulononaka.installapkinbackground
- Paste it under /system/app/base.apk and /system/priv-app/base.apk
- Delete the folder /data/app/com.github.paulononaka.installapkinbackground
- Reboot

You can now install/uninstall packages Tested in Android 8.1
